In [708]:
#Pacakges
import pandas as pd
import numpy as np

In [709]:
data_set=pd.read_csv("weatherHistory.csv")

In [710]:
#size of the dataset
data_set.shape

(96453, 12)

In [711]:
#Available columns
data_set.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [712]:
#smaple data
data_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [713]:
#droping the unwanted columns from the dataset 
data_set.drop(columns=['Formatted Date','Daily Summary','Precip Type','Loud Cover','Wind Bearing (degrees)'],axis=1,inplace=True)

In [714]:
data_set.head()

,Summary,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
0,Partly Cloudy,9.472222,7.388889,0.89,14.1197,15.8263,1015.13
1,Partly Cloudy,9.355556,7.227778,0.86,14.2646,15.8263,1015.63
2,Mostly Cloudy,9.377778,9.377778,0.89,3.9284,14.9569,1015.94
3,Partly Cloudy,8.288889,5.944444,0.83,14.1036,15.8263,1016.41
4,Mostly Cloudy,8.755556,6.977778,0.83,11.0446,15.8263,1016.51

In [715]:
#checking the null value
data_set.isnull().sum()

Summary                     0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Visibility (km)             0
Pressure (millibars)        0
dtype: int64

In [716]:
#filling the null value with previous values,pandas default function
#data_set['Precip Type'].fillna(method="ffill",inplace=True,axis=0)

In [717]:
#checking the null value
data_set.isnull().sum()

Summary                     0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Visibility (km)             0
Pressure (millibars)        0
dtype: int64

In [718]:

data_set.loc[data_set['Summary']=="Breezy and Dry",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Windy and Foggy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Dangerously Windy and Partly Cloudy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Windy and Dry",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Breezy and Overcast",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Breezy and Partly Cloudy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Breezy and Foggy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Breezy and Mostly Cloudy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Windy and Mostly Cloudy",'Summary']="Breezy"
data_set.loc[data_set['Summary']=="Drizzle",'Summary']="Rain"
data_set.loc[data_set['Summary']=="Light Rain",'Summary']="Rain"
data_set.loc[data_set['Summary']=="Humid and Overcast",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Dry and Mostly Cloudy",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Windy",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Dry and Partly Cloudy",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Windy and Partly Cloudy",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Windy and Overcast",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Humid and Mostly Cloudy",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Dry",'Summary']="Overcast"
data_set.loc[data_set['Summary']=="Humid and Partly Cloudy",'Summary']="Overcast"

data_set=data_set.loc[(data_set["Summary"]=="Partly Cloudy")|(data_set["Summary"]=="Mostly Cloudy")]
data_set['Summary'].value_counts()

Partly Cloudy    31733
Mostly Cloudy    28094
Name: Summary, dtype: int64

In [719]:
data=data_set.loc[(data_set["Summary"]=="Partly Cloudy")].index
data[0]

0

In [747]:
data_set=data_set.drop(data[:5000])

In [748]:
data_set['Summary'].value_counts()

Mostly Cloudy    28094
Partly Cloudy    26733
Name: Summary, dtype: int64

In [749]:
#data_set['Precip Type'].value_counts()

In [750]:
#For Regression algorith there should be dependent variable and independent variables
#In this project dataset dependent varible is Summary and all others are indepent varible ot to each other
#classify x and y axis
y=data_set.iloc[:,0]#First of the dataset i.e, Summary
x=data_set.iloc[:,1:]#except first row everything

In [751]:
x

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
2,9.377778,9.377778,0.89,3.9284,14.9569,1015.94
4,8.755556,6.977778,0.83,11.0446,15.8263,1016.51
17,15.550000,15.550000,0.63,11.1573,11.4471,1016.17
18,14.255556,14.255556,0.69,8.5169,11.2056,1015.82
19,13.144444,13.144444,0.70,7.6314,11.2056,1015.83
...,...,...,...,...,...,...
96448,26.016667,26.016667,0.43,10.9963,16.1000,1014.36
96449,24.583333,24.583333,0.48,10.0947,15.5526,1015.16
96450,22.038889,22.038889,0.56,8.9838,16.1000,1015.66
96451,21.522222,21.522222,0.60,10.5294,16.1000,1015.95
96452,20.438889,20.438889,0.61,5.8765,15.5204,1016.16

In [752]:
y

2        Mostly Cloudy
4        Mostly Cloudy
17       Mostly Cloudy
18       Mostly Cloudy
19       Mostly Cloudy
             ...
96448    Partly Cloudy
96449    Partly Cloudy
96450    Partly Cloudy
96451    Partly Cloudy
96452    Partly Cloudy
Name: Summary, Length: 54827, dtype: object

In [753]:
#Now x consist of string value convert in to numerical value
summary=list(set(y))
sumary_dict={}
for i in range(len(summary)):
    sumary_dict[summary[i]]=i
sumary_dict

{'Partly Cloudy': 0, 'Mostly Cloudy': 1}

In [754]:
# per=list(set(x['Precip Type']))
# per_dict={}
# for i in range(len(per)):
#     per_dict[per[i]]=i
# per_dict

In [755]:
#convert using label encoder
y=y.apply(lambda z:sumary_dict[z])
#x['Precip Type']=x['Precip Type'].apply(lambda z:per_dict[z])

In [756]:
#We can convert using inbuilt function also i.e using lable encoder function fron sklearn
#from sklearn.preprocessing import LabelEncoder
# le=LabelEncoder()
# y=le.fit_transform(data_set['Summary'])
# print(le.classes_)
# x['Precip Type']=le.fit_transform(x['Precip Type'])
# print(le.classes_)

In [757]:
#Normalizing the dataset between 0 to 1
# #NArmalization formula=(x-min(x))/(max(x)-min(x))
x=(x-np.min(x))/(np.max(x)-np.min(x))
x.dtypes

Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Visibility (km)             float64
Pressure (millibars)        float64
dtype: object

In [758]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
lr=LogisticRegression()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=75)
lr.fit(x_train,y_train)

LogisticRegression()

In [759]:
y_pred=lr.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.615994893306584

In [760]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [761]:
pr=lr.predict(x_test)
t=[round(j) for  j in pr]
t

[1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

In [762]:
from sklearn.metrics import accuracy_score
# t=np.argmax(pr)
accuracy_score(y_test,pr)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [763]:
y_test

67217    1
17974    0
52416    1
42136    0
35372    1
        ..
52915    0
61362    0
51794    0
68787    1
93651    1
Name: Summary, Length: 10966, dtype: int64

In [764]:
round(0.211)

0

In [765]:
from sklearn.naive_bayes import MultinomialNB

In [766]:
nb=MultinomialNB()
nb.fit(x_train,y_train)

MultinomialNB()

In [767]:
p=nb.predict(x_test)

In [768]:
p

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [769]:
accuracy_score(p,y_test)

0.5866314061645085

In [770]:
from sklearn.tree import DecisionTreeClassifier
clf_model = DecisionTreeClassifier(criterion="gini", random_state=42,max_depth=3, min_samples_leaf=5)   
clf_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [771]:
y_predict = clf_model.predict(x_test)

In [772]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,y_predict)

0.6173627576144447